id: A253DB928
title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
type: translation
pechas:
- I27DDE434
- I85CCD446
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:01:00.028808
  last_modified_at: 2023-01-04 13:01:00.028834
  collections:
  - Longsal Nyingpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I27DDE434/EE55: 251E
  I85CCD446/73A0: 251E
